server:
  port: 8090

spring:
  application:
    name: centralize-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hieuaxz00001/hieudx1-centralize-config.git
          search-paths: configurations
          default-label: main
